import 'dart:convert';
import 'dart:developer';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'features/auth/data/models/session_model.dart';

import 'features/auth/presentation/screens/login_screen.dart';
import 'features/menu/presentation/screens/home_screen.dart';
import 'features/admin/presentation/screens/admin_screen.dart';
import 'core/colors.dart';

// --- CONSTANTS ---
// Using the box name and key from HiveSessionStorage for consistency
const String _sessionBoxName = 'sessionBox'; // Matches HiveSessionStorage
const String _sessionKey = 'current_session'; // Matches HiveSessionStorage

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  
  // You need to register the adapter generated by build_runner
  // Make sure to run 'flutter pub run build_runner build'
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(SessionModelAdapter());
  }

  // Open the box with the correct name
  await Hive.openBox<SessionModel>(_sessionBoxName);

  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  Future<Widget> _determineStartScreen() async {
    // Use the correct box name and key
    final box = Hive.box<SessionModel>(_sessionBoxName);
    final sessionModel = box.get(_sessionKey);

    // 1. Check if session exists
    if (sessionModel == null || sessionModel.token.isEmpty) {
      log('No valid session found, navigating to LoginScreen.');
      return const LoginScreen();
    }

    try {
      // 2. Decode user JSON to check role
      // Check if the user string is not empty before decoding
      if (sessionModel.user.isEmpty) {
         log('Session found but user data is empty, navigating to LoginScreen.');
         return const LoginScreen();
      }
      
      final Map<String, dynamic> userMap = 
          Map<String, dynamic>.from(jsonDecode(sessionModel.user));

      final role = userMap['role'] as String? ?? '';

      // 3. Navigate based on role
      if (role == 'admin') {
        log("User is Admin, navigating to AdminScreen. Role: $role");
        return const AdminScreen();
      } else if (role == 'student') {
        log("User is Student, navigating to HomeScreen. Role: $role");
        return const HomeScreen();
      } else {
         // Default to HomeScreen for any other role or Login if role is missing/invalid
         log("User role is '$role', navigating to HomeScreen (or Login if unexpected).");
         return const HomeScreen(); // Assuming 'student' is the default if not admin
      }
    } catch (e) {
      // If error parsing role or data (e.g., malformed JSON), fallback to login screen
      log('Error parsing session data: ${e.toString()}, navigating to LoginScreen.');
      return const LoginScreen();
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return FutureBuilder<Widget>(
      future: _determineStartScreen(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          // Show a splash/loading screen while determining the start screen
          return MaterialApp(
            home: Scaffold(
              backgroundColor: AppColors.primaryDark,
              body: const Center(child: CircularProgressIndicator()),
            ),
          );
        }

        // Once the destination screen is determined, build the full MaterialApp
        return MaterialApp(
          title: 'OrderUp',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            colorScheme: ColorScheme.dark(
              primary: AppColors.mainOrange,
              secondary: AppColors.mainOrangeDark,
              surface: AppColors.secondaryDark,
            ),
            scaffoldBackgroundColor: AppColors.primaryDark,
            useMaterial3: true,
          ),
          home: snapshot.data,
        );
      },
    );
  }
}